version: "3.0"

expectations:
  population_size: 1000

actions:
  patient_id:
    run: sqlrunner:latest
      --output output/patient_id/rows.csv
      --dummy-data-file analysis/patient_id/dummy_rows.csv
      analysis/patient_id/query.sql
    outputs:
      highly_sensitive:
        rows: output/patient_id/rows.csv

  code_system_id:
    run: sqlrunner:latest
      --output output/code_system_id/rows.csv
      --dummy-data-file analysis/code_system_id/dummy_rows.csv
      analysis/code_system_id/query.sql
    outputs:
      highly_sensitive:
        rows: output/code_system_id/rows.csv

  coded_event_id:
    run: sqlrunner:latest
      --output output/coded_event_id/rows.csv
      --dummy-data-file analysis/coded_event_id/dummy_rows.csv
      analysis/coded_event_id/query.sql
    outputs:
      highly_sensitive:
        rows: output/coded_event_id/rows.csv
