version: "3.0"

expectations:
  population_size: 1000

actions:
  non_tpp_participants:
    run: sqlrunner:latest
      --output output/non_tpp_participants/rows.csv
      --dummy-data-file analysis/non_tpp_participants/dummy_rows.csv
      analysis/non_tpp_participants/query.sql
    outputs:
      moderately_sensitive:
        rows: output/non_tpp_participants/rows.csv

  code_system_id:
    run: sqlrunner:latest
      --output output/code_system_id/rows.csv
      --dummy-data-file analysis/code_system_id/dummy_rows.csv
      analysis/code_system_id/query.sql
    outputs:
      moderately_sensitive:
        rows: output/code_system_id/rows.csv

  coded_event_id:
    run: sqlrunner:latest
      --output output/coded_event_id/rows.csv
      --dummy-data-file analysis/coded_event_id/dummy_rows.csv
      analysis/coded_event_id/query.sql
    outputs:
      moderately_sensitive:
        rows: output/coded_event_id/rows.csv

  consultation_date:
    run: sqlrunner:latest
      --output output/consultation_date/rows.csv
      --dummy-data-file analysis/consultation_date/dummy_rows.csv
      analysis/consultation_date/query.sql
    outputs:
      moderately_sensitive:
        rows: output/consultation_date/rows.csv

  patients_by_surveys:
    run: sqlrunner:latest
      --output output/patients_by_surveys/rows.csv
      --dummy-data-file analysis/patients_by_surveys/dummy_rows.csv
      analysis/patients_by_surveys/query.sql
    outputs:
      moderately_sensitive:
        rows: output/patients_by_surveys/rows.csv

  row_response:
    run: sqlrunner:latest
      --output output/row_response/rows.csv
      --dummy-data-file analysis/row_response/dummy_rows.csv
      analysis/row_response/query.sql
    outputs:
      moderately_sensitive:
        rows: output/row_response/rows.csv

  is_consultation_id_fk:
    run: sqlrunner:latest
      --output output/is_consultation_id_fk/rows.csv
      --dummy-data-file analysis/is_consultation_id_fk/dummy_rows.csv
      analysis/is_consultation_id_fk/query.sql
    outputs:
      moderately_sensitive:
        rows: output/is_consultation_id_fk/rows.csv

  model_data_structure_from_query:
    run: sqlrunner:latest
      --output output/model_data_structure/rows.csv
      --dummy-data-file analysis/model_data_structure/dummy_rows.csv
      analysis/model_data_structure/query.sql
    outputs:
      highly_sensitive:
        rows: output/model_data_structure/rows.csv

  model_data_structure_from_dataset_definition:
    run: ehrql:v0
      generate-dataset
      --output output/model_data_structure/dataset.csv
      analysis/model_data_structure/dataset_definition.py
      --
      --day=0
    outputs:
      highly_sensitive:
        rows: output/model_data_structure/dataset.csv

  num_consultations_by_offset:
    run: sqlrunner:latest
      --output output/num_consultations_by_offset/rows.csv
      --dummy-data-file analysis/num_consultations_by_offset/dummy_rows.csv
      analysis/num_consultations_by_offset/query.sql
    outputs:
      moderately_sensitive:
        rows: output/num_consultations_by_offset/rows.csv

  numeric_value:
    run: sqlrunner:latest
      --output output/numeric_value/rows.csv
      --dummy-data-file analysis/numeric_value/dummy_rows.csv
      analysis/numeric_value/query.sql
    outputs:
      moderately_sensitive:
        rows: output/numeric_value/rows.csv

  duplicate_responses:
    run: sqlrunner:latest
      --output output/duplicate_responses/rows.csv
      --dummy-data-file analysis/duplicate_responses/dummy_rows.csv
      analysis/duplicate_responses/query.sql
    outputs:
      moderately_sensitive:
        rows: output/duplicate_responses/rows.csv
