version: "3.0"

expectations:
  population_size: 1000

actions:
  patient_id:
    run: sqlrunner:latest
      --output output/patient_id/rows.csv
      --dummy-data-file analysis/patient_id/dummy_rows.csv
      analysis/patient_id/query.sql
    outputs:
      highly_sensitive:
        rows: output/patient_id/rows.csv
